### ISSUE TITLE
Re-run the GraphSAGE++DAC and GraphSAGE++DAMC

### ISSUE THREAD

**Issue by ngocphat-fsdev** [ejwww/SAGE-plus#1]
Hello bro,
I found your repo because of your paper about GraphSAGE++. Your proposed model looks good to me. Thanks for your effort.

I run the code of GraphSAGE++DA successfully but the code of GraphSAGE++DAC and GraphSAGE++DAMC have failed. It is stuck in the code that uses torch.concat the feature vector representation. Please have a look at this code and update the latest code if you refixed it.

Thank you so much.

BR,
Peter

**Comment by ejwww** [comment]
Hello Peter,
Thank you so much for reaching out and for your interest in our GraphSAGE++ project. Thank you so much for reaching out and for your interest in our GraphSAGE++ project.
I've reviewed the the code and have made some modifications to address the issues you mentioned. Specifically, I've ensured that the feature vectors are correctly aligned before concatenation, which should resolve the errors during execution.
﻿
The updated version of the code has been tested and is now available in the repository. Please feel free to pull the latest changes and let me know if you encounter any further problems. I'm here to help and eager to make sure everything works smoothly for you.
﻿
Thank you once again for your valuable feedback and for helping us improve our work.
